"use client";

import { useState, useRef } from 'react';
import DocumentUploader from '@/components/DocumentUploader';
import ChatInterface from '@/components/ChatInterface';
import MindmapViewer from '@/components/MindmapViewer';
import SummaryPanel from '@/components/SummaryPanel';
import Sidebar from '@/components/Sidebar';
import ToastContainer from '@/components/ToastContainer';
import { useStore } from '@/store/useStore';
import { MessageSquare, Network, FileText, Brain, Zap, Lock } from 'lucide-react';
import { cn } from '@/lib/utils';
import { motion, AnimatePresence } from 'framer-motion';

type Tab = 'chat' | 'mindmap' | 'summary';

const tabs: { id: Tab; label: string; icon: React.ElementType }[] = [
  { id: 'chat', label: 'Chat', icon: MessageSquare },
  { id: 'mindmap', label: 'Mindmap', icon: Network },
  { id: 'summary', label: 'Summary', icon: FileText },
];

const features = [
  { icon: Brain, title: 'Smart Parsing', desc: 'Extracts structure & entities accurately from any PDF.' },
  { icon: Network, title: 'Visual Maps', desc: 'Auto-generates interactive knowledge mindmaps.' },
  { icon: MessageSquare, title: 'Context Chat', desc: 'Ask questions with answers grounded in document text.' },
  { icon: Lock, title: '100% Private', desc: 'Everything runs locally. Zero cloud, zero data leaks.' },
  { icon: Zap, title: 'Fast RAG', desc: 'FAISS vector search returns relevant context instantly.' },
  { icon: FileText, title: 'AI Summary', desc: 'Executive summaries generated by local LLM.' },
];

export default function Home() {
  const { currentDocumentId, currentDocument } = useStore();
  const [activeTab, setActiveTab] = useState<Tab>('chat');
  const [showUploader, setShowUploader] = useState(false);
  const uploaderRef = useRef<HTMLDivElement>(null);

  const handleNewDocument = () => {
    setShowUploader(true);
    setTimeout(() => uploaderRef.current?.scrollIntoView({ behavior: 'smooth' }), 100);
  };

  return (
    <main className="flex h-screen overflow-hidden bg-slate-950 text-slate-50">
      <Sidebar onNewDocument={handleNewDocument} />

      <div className="flex-1 flex flex-col h-full overflow-hidden">
        {/* Top Navbar */}
        <header className="h-14 border-b border-slate-800/60 bg-slate-900/40 backdrop-blur-sm flex items-center px-6 justify-between shrink-0">
          <div className="flex items-center gap-3">
            <h2 className="text-sm font-medium text-slate-300">
              {currentDocument
                ? currentDocument.filename
                : 'AI Document Intelligence Engine'}
            </h2>
            {currentDocument?.processing_status === 'completed' && (
              <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-500/10 text-emerald-400 border border-emerald-500/20 font-medium">
                Ready
              </span>
            )}
          </div>

          {/* Tab switcher */}
          {currentDocumentId && (
            <div className="flex bg-slate-800/60 p-0.5 rounded-lg border border-slate-700/50 gap-0.5">
              {tabs.map(({ id, label, icon: Icon }) => (
                <button
                  key={id}
                  onClick={() => setActiveTab(id)}
                  className={cn(
                    'px-3 py-1.5 rounded-md text-xs font-medium flex items-center gap-1.5 transition-all',
                    activeTab === id
                      ? 'bg-slate-700 text-white shadow-sm'
                      : 'text-slate-400 hover:text-slate-200'
                  )}
                >
                  <Icon size={13} />
                  {label}
                </button>
              ))}
            </div>
          )}
        </header>

        {/* Main Content */}
        <div className="flex-1 overflow-y-auto relative custom-scrollbar">
          {/* Ambient background */}
          <div className="absolute inset-0 pointer-events-none -z-10 overflow-hidden">
            <div className="absolute top-1/4 -left-1/4 w-[600px] h-[600px] bg-blue-600/5 rounded-full blur-[120px]" />
            <div className="absolute bottom-1/4 -right-1/4 w-[600px] h-[600px] bg-indigo-600/5 rounded-full blur-[120px]" />
          </div>

          {!currentDocumentId ? (
            /* ── Landing / No Document Selected ── */
            <div className="p-8 max-w-5xl mx-auto">
              <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="text-center mb-10"
              >
                <div className="inline-flex items-center gap-2 bg-blue-500/10 border border-blue-500/20 rounded-full px-4 py-1.5 text-xs text-blue-300 font-medium mb-6">
                  <div className="w-1.5 h-1.5 rounded-full bg-blue-400 animate-pulse" />
                  Fully local · No cloud · No API keys
                </div>
                <h1 className="text-5xl font-bold text-transparent bg-clip-text bg-gradient-to-b from-white to-slate-500 mb-4 tracking-tight leading-tight">
                  Unlock Intelligence<br />from Any PDF
                </h1>
                <p className="text-slate-400 text-lg max-w-xl mx-auto leading-relaxed">
                  Upload your research papers, contracts, or reports. Get mindmaps, summaries, and answers — all running locally on your machine.
                </p>
              </motion.div>

              {/* Uploader */}
              <div ref={uploaderRef}>
                <DocumentUploader />
              </div>

              {/* Features grid */}
              <div className="grid grid-cols-2 md:grid-cols-3 gap-4 mt-8">
                {features.map(({ icon: Icon, title, desc }, i) => (
                  <motion.div
                    key={title}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.1 + i * 0.05 }}
                    className="p-5 rounded-2xl bg-white/[0.03] border border-white/[0.06] hover:bg-white/[0.06] transition-colors"
                  >
                    <Icon className="w-7 h-7 text-blue-400 mb-3" />
                    <h3 className="text-sm font-semibold text-white mb-1">{title}</h3>
                    <p className="text-xs text-slate-500 leading-relaxed">{desc}</p>
                  </motion.div>
                ))}
              </div>
            </div>
          ) : (
            /* ── Document View ── */
            <div className="h-full p-6">
              <AnimatePresence mode="wait">
                {activeTab === 'chat' && (
                  <motion.div
                    key="chat"
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: -10 }}
                    className="h-full"
                  >
                    <ChatInterface />
                  </motion.div>
                )}
                {activeTab === 'mindmap' && (
                  <motion.div
                    key="mindmap"
                    initial={{ opacity: 0, x: 10 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: 10 }}
                    className="h-full"
                  >
                    <MindmapViewer />
                  </motion.div>
                )}
                {activeTab === 'summary' && (
                  <motion.div
                    key="summary"
                    initial={{ opacity: 0, x: 10 }}
                    animate={{ opacity: 1, x: 0 }}
                    exit={{ opacity: 0, x: 10 }}
                    className="max-w-2xl mx-auto"
                  >
                    <SummaryPanel />
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          )}
        </div>
      </div>

      {/* Global Toast Notifications */}
      <ToastContainer />
    </main>
  );
}
